apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejwks-ingress
  namespace: quitty
spec:
  tls:
    - hosts: ["ejwks.example.com"]
      secretName: ejwks-tls
  rules:
    - host: ejwks.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ejwks
                port:
                  number: 8000
